### ISSUE TITLE
GDActionNodeWait uses global RNG instead of local RNG

### ISSUE THREAD

**Issue by nstryder** [duongvituan/godot-action-animation-framework#3]
In the file `GDActionNodeWait.gd`, `randomize()` and `rand_range()` is called which use the global RNG of godot. I'm not sure if this node is instantiated everytime a wait is called, but if it is, then the global RNG will get reseeded each time which interferes with the main application making use of global RNG properly.

**Comment by duongvituan** [comment]
I agree with you, func randomize() should be called from the main app.

**Comment by duongvituan** [comment]
I think it can be fixed like this: [link](https://github.com/duongvituan/godot-action-animation-framework/pull/4)
Do you have any suggestions? cc @nstryder n
